name: Dependency checks

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "23 9 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependencies:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: rustup show active-toolchain
      - uses: taiki-e/install-action@3f74d7c16a4242f1c95561e98edc25d36adb4375 # v2.87.12
        with:
          tool: cargo-deny,cargo-machete,actionlint
      - run: actionlint
      - run: cargo deny --locked check
      - run: cargo machete --with-metadata
